print("Sandeep Muhal")
print("Perfrom operation:-)))) ")

Name=input("Enter name:-")
a=int(input("Enter a number:-"))
b=int(input("Enter a number:-"))
c=float(input("Enter a number:-"))
print("Sum=", a+b)
print("Division=", a/b)
print("Substracation=", a-b)
print("Multiplication=", a*b)
print("Module=", a%b)
print(type(Name))
print(type(a))
print(type(c))